#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ShouldIWashMyCar.Android.Resource", IsApplication=true)]

namespace ShouldIWashMyCar.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Labs.Droid.Resource.Attribute.state_current_month = global::ShouldIWashMyCar.Android.Resource.Attribute.state_current_month;
			global::Xamarin.Forms.Labs.Droid.Resource.Attribute.state_highlighted = global::ShouldIWashMyCar.Android.Resource.Attribute.state_highlighted;
			global::Xamarin.Forms.Labs.Droid.Resource.Attribute.state_range_first = global::ShouldIWashMyCar.Android.Resource.Attribute.state_range_first;
			global::Xamarin.Forms.Labs.Droid.Resource.Attribute.state_range_last = global::ShouldIWashMyCar.Android.Resource.Attribute.state_range_last;
			global::Xamarin.Forms.Labs.Droid.Resource.Attribute.state_range_middle = global::ShouldIWashMyCar.Android.Resource.Attribute.state_range_middle;
			global::Xamarin.Forms.Labs.Droid.Resource.Attribute.state_selectable = global::ShouldIWashMyCar.Android.Resource.Attribute.state_selectable;
			global::Xamarin.Forms.Labs.Droid.Resource.Attribute.state_today = global::ShouldIWashMyCar.Android.Resource.Attribute.state_today;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_active_month_bg = global::ShouldIWashMyCar.Android.Resource.Color.calendar_active_month_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_bg = global::ShouldIWashMyCar.Android.Resource.Color.calendar_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_divider = global::ShouldIWashMyCar.Android.Resource.Color.calendar_divider;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_highlighted_day_bg = global::ShouldIWashMyCar.Android.Resource.Color.calendar_highlighted_day_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_inactive_month_bg = global::ShouldIWashMyCar.Android.Resource.Color.calendar_inactive_month_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_selected_day_bg = global::ShouldIWashMyCar.Android.Resource.Color.calendar_selected_day_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_selected_range_bg = global::ShouldIWashMyCar.Android.Resource.Color.calendar_selected_range_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_active = global::ShouldIWashMyCar.Android.Resource.Color.calendar_text_active;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_inactive = global::ShouldIWashMyCar.Android.Resource.Color.calendar_text_inactive;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_selected = global::ShouldIWashMyCar.Android.Resource.Color.calendar_text_selected;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_selector = global::ShouldIWashMyCar.Android.Resource.Color.calendar_text_selector;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_unselectable = global::ShouldIWashMyCar.Android.Resource.Color.calendar_text_unselectable;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_day_headers_paddingbottom = global::ShouldIWashMyCar.Android.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_month_title_bottommargin = global::ShouldIWashMyCar.Android.Resource.Dimension.calendar_month_title_bottommargin;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_month_topmargin = global::ShouldIWashMyCar.Android.Resource.Dimension.calendar_month_topmargin;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_text_medium = global::ShouldIWashMyCar.Android.Resource.Dimension.calendar_text_medium;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_text_small = global::ShouldIWashMyCar.Android.Resource.Dimension.calendar_text_small;
			global::Xamarin.Forms.Labs.Droid.Resource.Drawable.calendar_bg_selector = global::ShouldIWashMyCar.Android.Resource.Drawable.calendar_bg_selector;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.calendar_grid = global::ShouldIWashMyCar.Android.Resource.Id.calendar_grid;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.calendar_view = global::ShouldIWashMyCar.Android.Resource.Id.calendar_view;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.title = global::ShouldIWashMyCar.Android.Resource.Id.title;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.calendar_picker = global::ShouldIWashMyCar.Android.Resource.Layout.calendar_picker;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.dialog = global::ShouldIWashMyCar.Android.Resource.Layout.dialog;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.month = global::ShouldIWashMyCar.Android.Resource.Layout.month;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.week = global::ShouldIWashMyCar.Android.Resource.Layout.week;
			global::Xamarin.Forms.Labs.Droid.Resource.String.day_name_format = global::ShouldIWashMyCar.Android.Resource.String.day_name_format;
			global::Xamarin.Forms.Labs.Droid.Resource.String.full_date_format = global::ShouldIWashMyCar.Android.Resource.String.full_date_format;
			global::Xamarin.Forms.Labs.Droid.Resource.String.invalid_date = global::ShouldIWashMyCar.Android.Resource.String.invalid_date;
			global::Xamarin.Forms.Labs.Droid.Resource.String.library_name = global::ShouldIWashMyCar.Android.Resource.String.library_name;
			global::Xamarin.Forms.Labs.Droid.Resource.String.month_name_format = global::ShouldIWashMyCar.Android.Resource.String.month_name_format;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell = global::ShouldIWashMyCar.Android.Resource.Style.CalendarCell;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell_CalendarDate = global::ShouldIWashMyCar.Android.Resource.Style.CalendarCell_CalendarDate;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell_DayHeader = global::ShouldIWashMyCar.Android.Resource.Style.CalendarCell_DayHeader;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarTitle = global::ShouldIWashMyCar.Android.Resource.Style.CalendarTitle;
			global::Xamarin.Forms.Labs.Droid.Resource.Styleable.calendar_cell = global::ShouldIWashMyCar.Android.Resource.Styleable.calendar_cell;
			global::Xamarin.Forms.Labs.Droid.Resource.Styleable.calendar_cell_state_current_month = global::ShouldIWashMyCar.Android.Resource.Styleable.calendar_cell_state_current_month;
			global::Xamarin.Forms.Labs.Droid.Resource.Styleable.calendar_cell_state_highlighted = global::ShouldIWashMyCar.Android.Resource.Styleable.calendar_cell_state_highlighted;
			global::Xamarin.Forms.Labs.Droid.Resource.Styleable.calendar_cell_state_range_first = global::ShouldIWashMyCar.Android.Resource.Styleable.calendar_cell_state_range_first;
			global::Xamarin.Forms.Labs.Droid.Resource.Styleable.calendar_cell_state_range_last = global::ShouldIWashMyCar.Android.Resource.Styleable.calendar_cell_state_range_last;
			global::Xamarin.Forms.Labs.Droid.Resource.Styleable.calendar_cell_state_range_middle = global::ShouldIWashMyCar.Android.Resource.Styleable.calendar_cell_state_range_middle;
			global::Xamarin.Forms.Labs.Droid.Resource.Styleable.calendar_cell_state_selectable = global::ShouldIWashMyCar.Android.Resource.Styleable.calendar_cell_state_selectable;
			global::Xamarin.Forms.Labs.Droid.Resource.Styleable.calendar_cell_state_today = global::ShouldIWashMyCar.Android.Resource.Styleable.calendar_cell_state_today;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int state_current_month = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int state_highlighted = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int state_range_first = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int state_range_last = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int state_range_middle = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int state_selectable = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int state_today = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int calendar_active_month_bg = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int calendar_bg = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int calendar_divider = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int calendar_highlighted_day_bg = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int calendar_inactive_month_bg = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int calendar_selected_day_bg = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int calendar_selected_range_bg = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int calendar_text_active = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int calendar_text_inactive = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int calendar_text_selected = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int calendar_text_selector = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int calendar_text_unselectable = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int calendar_day_headers_paddingbottom = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int calendar_month_title_bottommargin = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int calendar_month_topmargin = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int calendar_text_medium = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_text_small = 2131034116;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calendar_bg_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CarSideView = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Cloud = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Radar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Rain = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Sun = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Sunny = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int calendar_grid = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int calendar_view = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int myButton = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int title = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int month = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int week = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060006
			public const int app_name = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int day_name_format = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int full_date_format = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int hello = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int invalid_date = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int month_name_format = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] calendar_cell = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 1
			public const int calendar_cell_state_current_month = 1;
			
			// aapt resource value: 6
			public const int calendar_cell_state_highlighted = 6;
			
			// aapt resource value: 3
			public const int calendar_cell_state_range_first = 3;
			
			// aapt resource value: 5
			public const int calendar_cell_state_range_last = 5;
			
			// aapt resource value: 4
			public const int calendar_cell_state_range_middle = 4;
			
			// aapt resource value: 0
			public const int calendar_cell_state_selectable = 0;
			
			// aapt resource value: 2
			public const int calendar_cell_state_today = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
